version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=mongodb://mongo:27017/wanderlust
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: